# http://travis-ci.org/#!/elasticsales/flask-mongorest
language: python
services: mongodb
python:
    - 2.7
install:
    - pip install -e .
    - pip install -e '.[test]'
script:
    - python setup.py nosetests
